"""Generate a tailored-resume Word document from plain text."""

from __future__ import annotations

import re
from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt

BODY_FONT = "Calibri"
BODY_SIZE = Pt(11)
H2_SIZE = Pt(13)
H1_SIZE = Pt(16)


def _add_horizontal_rule(paragraph) -> None:
    """Render a single horizontal line by setting a bottom border on a paragraph.

    python-docx has no first-class HR; this manipulates the underlying XML.
    """
    p_pr = paragraph._p.get_or_add_pPr()
    p_bdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "auto")
    p_bdr.append(bottom)
    p_pr.append(p_bdr)


def _is_section_header(line: str) -> bool:
    """A line counts as a section header if it's all-caps OR ends with a colon.

    We cap length to avoid mis-classifying a normal sentence that happens to
    end with ':'. A header is also expected to contain at least one letter.
    """
    stripped = line.strip()
    if not stripped or len(stripped) > 60:
        return False
    if not re.search(r"[A-Za-z]", stripped):
        return False
    if stripped.endswith(":"):
        return True
    letters_only = re.sub(r"[^A-Za-z]", "", stripped)
    return bool(letters_only) and letters_only.isupper()


def _style_run(run, *, font_name: str = BODY_FONT, size=BODY_SIZE, bold: bool = False) -> None:
    run.font.name = font_name
    run.font.size = size
    run.bold = bold
    # Belt-and-braces: also set East Asian font name so Word respects it.
    rPr = run._element.get_or_add_rPr()
    rFonts = rPr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = OxmlElement("w:rFonts")
        rPr.append(rFonts)
    rFonts.set(qn("w:ascii"), font_name)
    rFonts.set(qn("w:hAnsi"), font_name)
    rFonts.set(qn("w:cs"), font_name)


def generate_tailored_docx(tailored_text: str, job: dict[str, Any]) -> bytes:
    """Render a tailored resume as a styled .docx, returned as raw bytes.

    Args:
        tailored_text: The full plain-text tailored resume (from the agent).
        job: Job dict — only ``title`` and ``company`` are read, for the footer.

    Returns:
        The .docx file contents as bytes (suitable for st.download_button).
    """
    doc = Document()

    # 1-inch margins on all sides.
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Set the default body font on the Normal style.
    normal = doc.styles["Normal"]
    normal.font.name = BODY_FONT
    normal.font.size = BODY_SIZE

    lines = (tailored_text or "").splitlines()

    # Pull out the candidate name = first non-empty line.
    name = ""
    name_idx = -1
    for i, line in enumerate(lines):
        if line.strip():
            name = line.strip()
            name_idx = i
            break

    # ---- Heading 1: name ----
    heading_para = doc.add_paragraph()
    heading_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    heading_run = heading_para.add_run(name or "Resume")
    _style_run(heading_run, size=H1_SIZE, bold=True)

    # ---- Horizontal rule ----
    rule_para = doc.add_paragraph()
    _add_horizontal_rule(rule_para)

    # ---- Body ----
    body_lines = lines[name_idx + 1:] if name_idx >= 0 else lines
    for raw in body_lines:
        line = raw.rstrip()
        if not line.strip():
            # Preserve blank lines as empty paragraphs for vertical spacing.
            doc.add_paragraph()
            continue

        if _is_section_header(line):
            para = doc.add_paragraph()
            run = para.add_run(line.strip())
            _style_run(run, size=H2_SIZE, bold=True)
        else:
            para = doc.add_paragraph()
            run = para.add_run(line)
            _style_run(run, size=BODY_SIZE)

    # ---- Footer ----
    footer_para = doc.sections[0].footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    job_title = (job.get("title") or "Unknown role").strip()
    job_company = (job.get("company") or "Unknown company").strip()
    footer_run = footer_para.add_run(
        f"Tailored for: {job_title} at {job_company} | Generated by ResuMatch"
    )
    _style_run(footer_run, size=Pt(9))

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


__all__ = ["generate_tailored_docx"]
